apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 80       # External cluster port
      targetPort: 5001  # Matches container port
  type: ClusterIP